version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - testing

  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: testing
      MYSQL_USER: testing-admin
      MYSQL_PASSWORD: testing-admin-123
      MYSQL_ROOT_PASSWORD: testing-123
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3036:3306"
    networks:
      - testing

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "8008:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
      - ./logs:/var/log/nginx
    depends_on:
      - web
    networks:
      - testing

networks:
  testing:
    driver: bridge

volumes:
  db_data:
